### ISSUE TITLE
UI Contas - Correção na ação de retorno de página

### ISSUE THREAD

**Issue by graziellyoliveira** [wisemonkeys-co/wise-billing#129]
<h2>Descrição</h2>

Ao clicar no botão de retornar após salvar edição de conta, é apresentado um erro ao carregar página.

<h2>Objetivos</h2>

- Manter a integridade nas ações de front-end. 

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-app

<h2>Detalhamento</h2>

| Tela com erro | Gif da aplicação |
|---------------|-----------------|
| ![2024-06-21_18-03](https://github.com/wisemonkeys-co/wise-billing/assets/99608391/ff4ea332-6dfa-4ef9-bf68-1f6043f0817f) | ![Peek 21-06-2024 18-02](https://github.com/wisemonkeys-co/wise-billing/assets/99608391/a8e2dae4-e39d-4f76-a206-ceb3ab378164) |

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>


https://github.com/user-attachments/assets/cef408ef-de2f-4486-ae02-0190cb4dc23c
