### ISSUE TITLE
UI Integrações - Ajuste de descrições

### ISSUE THREAD

**Issue by paulowhyte** [wisemonkeys-co/wise-billing#130]
<h2>Descrição</h2>

Ajustar as descrições  para se adequarem a nova arquitetura de integração ( arquivos ou streaming de eventos )

<h2>Objetivos</h2>

- Adequação no entendimento de conceito
- Usabilidade

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-app

<h2>Detalhamento</h2>

![Screenshot 2024-07-03 at 14 38 15](https://github.com/wisemonkeys-co/wise-billing/assets/3217623/940b1dc8-82e4-49db-af66-af36fda89e84)

**Comment by alvarobhz** [comment]
<h2>Homologação </h2>

| Arquivos de Eventos > Integrações e Definição de esquema de arquivos > Esquema de dados |
|--------|
| ![2024-07-11_10-29](https://github.com/wisemonkeys-co/wise-billing/assets/18542221/ae7eb4f3-8ea8-45b8-819d-a4c2ed87efdd) |
