### ISSUE TITLE
Correção de componente de inserção em coleções chave/valor

### ISSUE THREAD

**Issue by paulowhyte** [wisemonkeys-co/wise-billing#135]
<h2>Descrição</h2>

Para o banco de dados vazio a inserção de novas chaves/valores não funciona

<h2>Objetivos</h2>

- Integridade da UI

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-bff-api
- [x] ocs-app

<h2>Detalhamento</h2>

![Screenshot 2024-07-04 at 11 37 44](https://github.com/wisemonkeys-co/wise-billing/assets/3217623/238b0be2-5dd6-41ac-ba3a-8e7617420201)

**Comment by athmatias** [comment]
@paulowhyte nós precisamos definir um esquema para cada um desses componentes de crud, o component hoje assume que temos dados no banco (pelo menos 1 row) e cria os campos de form bem como as colunas de acordo com esse arranjo.

Como o banco é vazio não temos nenhuma row na collection e logo não temos nenhum meio de "deduzir" o schema.

Existem duas maneiras que pensei em fazer essa tarefa:

1 - A forma mais trabalhosa e menos segura é criar o esquema pelo frontend, ai teríamos um modal que iria abrir quando clicarmos no + e ao invés do modal convencional, abriria esse modal de definição do esquema, o backend valida o esquema dessas tabelas dinâmicas? O problema disso seria as validações iniciais pois teríamos que ou guiar o usuário sobre qual o tipo de cada campo ele estaria criando (string, number, object etc). Isso abre brechas de segurança para inserir scripts maliciosos, ai o trabalho extra para sanitizar tudo antes de enviar ao backend.

2 - Teriamos uma tabela de esquemas onde o FE iria receber esses esquemas e iria montar as tabelas e forms de acordo com o esquema definido no BE, mais seguro e só teria que receber esse esquema via um GET schemes por exemplo.

Se você tiver algum outra sugestão ou direcionamento é só me falar.

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>

| Criado um provedor após a limpeza da collection  |
|--------|
| ![Screenshot from 2024-08-19 16-19-37](https://github.com/user-attachments/assets/9fb11936-f491-4553-9e9a-81d63c4ec4ae) |
