### ISSUE TITLE
UI ordens de venda - Filtrar exportação para excel para clientes 

### ISSUE THREAD

**Issue by paulowhyte** [wisemonkeys-co/wise-billing#146]
<h2>Descrição</h2>

 Filtrar exportação para excel para clientes ( accessGroup = "invoice" )
Atualmente exporta também ítens de detalhamento interno ( accessGroup = "admin" )

<h2>Objetivos</h2>

- Adequação de funcionalidade para envio a clientes

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-app

<h2>Detalhamento</h2>

![Screenshot 2024-07-16 at 17 28 02](https://github.com/user-attachments/assets/c5acd21b-acfa-4193-9493-62c6c7010478)

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>


| Download trazendo corretamente somente o accessGroup = "invoice". Tela com comparativo do excel e a ordem. |
|--------|
| ![2024-08-14_10-17](https://github.com/user-attachments/assets/aa682649-e0f6-47d7-92d1-154ca38219a6) |
