### ISSUE TITLE
UI detalhamento de ordens de venda - Exportação para excel

### ISSUE THREAD

**Issue by paulowhyte** [wisemonkeys-co/wise-billing#147]
<h2>Descrição</h2>

Permitir a exportação para excel do detalhamento das ordens de venda

<h2>Objetivos</h2>

- Permitir análise offline de ordens de venda

<h2>Requisitos</h2>

- Incluir colunas do evento ( nome e descrição )
- Incluir coluna de grupo de visibilidade ( accessGroup )

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-app

<h2>Detalhamento</h2>

![Screenshot 2024-07-17 at 16 37 31](https://github.com/user-attachments/assets/5ebe74fb-f83f-4362-8998-1b4689b71aee)

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>


| Download trazendo corretamente o accessGroup = "invoice" e "admin". Tela com comparativo do excel e a ordem. |
|--------|
| ![2024-08-15_16-45](https://github.com/user-attachments/assets/7c86ad79-d4a2-4c01-b24d-d8b8952b410c) |
