### ISSUE TITLE
UI usuários - Atualizar exibição de usuários após exclusão

### ISSUE THREAD

**Issue by paulowhyte** [wisemonkeys-co/wise-billing#148]
<h2>Descrição</h2>

Ajustes na UI de usuários :  
- Atualizar exibição de usuários após exclusão
- Modal de criação não reinicializando entre abas Usuários/Clientes

<h2>Objetivos</h2>

- Integridade da UI

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-app

<h2>Detalhamento</h2>

![2024-07-05 15 57 03](https://github.com/user-attachments/assets/23f556ec-34e5-4f99-9143-6689d5a61b95)

![Screenshot 2024-07-05 at 16 03 17](https://github.com/user-attachments/assets/bce69f51-17ce-46af-be96-1a0188c0b0b6)

![Screenshot 2024-07-05 at 16 02 43](https://github.com/user-attachments/assets/1d2423c0-8602-4b36-acdd-b35183ef6ccd)

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>

Modal correto na aba usuários e clientes e exibição de usuários atualizada  após exclusão

![2024-08-14_09-59](https://github.com/user-attachments/assets/2990ca69-577e-46d6-b5b1-89970e828377)
 ![Screenshot from 2024-08-14 10-01-25](https://github.com/user-attachments/assets/23d13c6d-f979-4ac7-ad98-909b5639d4d5)
 
https://github.com/user-attachments/assets/d993617d-70a3-4331-beea-496a2040bd76
