### ISSUE TITLE
UI Usuários - Ajustes na listagem de usuários

### ISSUE THREAD

**Issue by paulowhyte** [wisemonkeys-co/wise-billing#161]
<h2>Descrição</h2>

Ajustar a listagem de usuários 
- Último login - tratamento quando logins = 0  Último login = "Nunca" .Formatar saída ( seg, min, dias )
- Prevenir auto deleção do usuário logado
- Verificar update 
- Verificar delete 

<h2>Objetivos</h2>

- Integridade da UI

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-bff-api
- [x] ocs-app

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>


Último login atualizado/ bloqueado exclusão do usuário logado

![Screenshot from 2024-10-10 08-41-46](https://github.com/user-attachments/assets/caac864a-0d42-471f-a6bd-9e747c4d7d73)

Exclusão de usuário 

![Screenshot from 2024-10-10 08-50-54](https://github.com/user-attachments/assets/24908412-6499-42af-890f-a8e9b5f9c5a2)

Atualização após alteração 

![Screenshot from 2024-10-10 08-51-02](https://github.com/user-attachments/assets/7c4b5b93-246a-4e85-a95f-5a0b5ccb6215)
