### ISSUE TITLE
Correção na criação de contas por templates

### ISSUE THREAD

**Issue by paulowhyte** [wisemonkeys-co/wise-billing#170]
<h2>Descrição</h2>

Os ajustes necessários nas interfaces de pesquisa de contas causaram problema interface modal de inserção de novas contas baseadas em templates (cópia).
Na interface modal só aparecem as contas previamente pesquisadas na interface principal .
Deve ser implementada uma pesquisa semelhante a da interface principal . 

<h2>Objetivos</h2>

- Integridade da UI

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-app

<h2>Detalhamento</h2>

![Screenshot 2024-09-30 at 11 59 12](https://github.com/user-attachments/assets/277b5406-d826-41cd-89c7-b7b4207ce3f9)

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>


|Visualização dos templates para criação de conta  |  Conta criada via interface usando o template listado
|--------|-------|
|![Screenshot from 2024-10-02 18-00-15](https://github.com/user-attachments/assets/53b0c820-4c2a-404f-802f-238c80909afe)|![Screenshot from 2024-10-02 18-04-56](https://github.com/user-attachments/assets/abe2fdaf-94b9-4db6-94c8-b16cf4084323)
