### ISSUE TITLE
Ajustes na atualização de usuários

### ISSUE THREAD

**Issue by paulowhyte** [wisemonkeys-co/wise-billing#172]
<h2>Descrição</h2>

Verificar todas operações de gestão de usuários no provedor de identidade Auth0. 

<h2>Objetivos</h2>

- Integridade da UI

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-bff-api

<h2>Detalhamento</h2>

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>

| Função de criar usuário validada  | Função de editar usuário validada |
|--------|--------|
|![Screenshot from 2024-10-10 09-15-46](https://github.com/user-attachments/assets/1fc2711d-1b21-443c-b58c-ab88785ff61e)|![Screenshot from 2024-10-10 09-00-47](https://github.com/user-attachments/assets/e2e9c257-4629-4d7b-8fd3-b4a524f2c42f)|

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>

| Função de criar usuário validada  | Função de editar usuário validada |
|--------|--------|
|![Screenshot from 2024-10-10 09-15-46](https://github.com/user-attachments/assets/1fc2711d-1b21-443c-b58c-ab88785ff61e)|![Screenshot from 2024-10-10 09-00-47](https://github.com/user-attachments/assets/e2e9c257-4629-4d7b-8fd3-b4a524f2c42f)|
