### ISSUE TITLE
UI Origens (Realms) - Mostrar descrições para os tipos de campos mapeados

### ISSUE THREAD

**Issue by paulowhyte** [wisemonkeys-co/wise-billing#173]
<h2>Descrição</h2>

No cadastro de origens (realms) , mostrar descrições no lugar dos códigos armazenados no banco de dados.

<h2>Objetivos</h2>

- Usabilidade da UI

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-app

<h2>Detalhamento</h2>

Mapear elementos do atributo events.fieldMapping.types  para

"service"           "Serviço"
"metric"            "Métrica"
"date"              "Data"
"value"             "Valor"
"TPCustomer"        "Terceiro"
"modifier"          "Modificador"
"billingScope"      "Escopo"
"customer"          "Cliente"
"groupby"           "Agrupamento"
"id"                "Identificador"
"info"              "Informação"
"count"             "Quantidade"

![Screenshot 2024-10-02 at 16 55 08](https://github.com/user-attachments/assets/d3b8a493-1f1e-434c-a468-6ea3c79388ec)

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>

Elementos do atributo events.fieldMapping.types atualizados

![Screenshot from 2024-10-10 08-35-31](https://github.com/user-attachments/assets/b7a71f79-2219-4b36-b569-c698c56eb3ee)
