### ISSUE TITLE
Internacionalização

### ISSUE THREAD

**Issue by paulowhyte** [wisemonkeys-co/wise-billing#180]
<h2>Descrição</h2>

Implementar internacionalização de moeda e idioma 

<h2>Objetivos</h2>

- Atender novos mercados externos

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-bff-api
- [x] ocs-app

<h2>Detalhamento</h2>

Implementar prioritariamente a exibição de moeda para os países:

- México
- Estados Unidos
- Espanha
- Portugal

Propriedade na coleção settings:
````
    "intl" : {
        "currency" : "BRL",
        "locale" : "pt-BR",
        "location" : "America/Sao_Paulo"
    }
````

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>

Alteração para a moeda USD

![Screenshot from 2024-12-06 11-23-52](https://github.com/user-attachments/assets/d8bca821-2563-434f-9677-f991693f4cf6)
![Screenshot from 2024-12-06 11-23-17](https://github.com/user-attachments/assets/7a0d20b2-0af0-421b-9a1d-770dc070035a)
![Screenshot from 2024-12-06 11-23-00](https://github.com/user-attachments/assets/a23061d7-61cc-42f8-9b52-f0ea0905e98d)
![Screenshot from 2024-12-06 11-22-39](https://github.com/user-attachments/assets/d54663fd-2d1f-4631-a867-6348e3d1672e)
![Screenshot from 2024-12-06 11-21-45](https://github.com/user-attachments/assets/5dfb2ae8-a3bb-4cc1-8b66-9878d421cb65)
