### ISSUE TITLE
Correção no processo de criação de novos serviços

### ISSUE THREAD

**Issue by graziellyoliveira** [wisemonkeys-co/wise-billing#181]
<h2>Descrição</h2>
Problema na interface de inserção de novos serviços. 
Ao criar um novo item preenchendo apenas os campos da aba _propriedades_, o botão de salvar não está respondendo e portanto não grava as informações no banco. 
Se navegarmos pelas outras abas para preenchimento dos dados, é apresentado um erro de comunicação. 

<h2>Objetivos</h2>

- Integridade da UI

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-app

<h2>Detalhamento</h2>

|Erro de comunicação  |  Processo de criação 
|--------|-------|
|![Captura de tela de 2024-10-24 11-09-41](https://github.com/user-attachments/assets/b9f1b62f-11a1-409d-baad-436603a3a17b) | ![Peek 24-10-2024 11-12](https://github.com/user-attachments/assets/c5c5eff1-4f11-4451-ae84-13fe37ff1dd5)

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>

| Criação de serviço  | Serviço criado e sendo exibido pela interface |
|--------|--------|
|![Screenshot from 2024-12-06 11-54-49](https://github.com/user-attachments/assets/dc73a08d-45ed-418a-9193-6b6d8a165820)|![Screenshot from 2024-12-06 12-13-22](https://github.com/user-attachments/assets/2d895574-d1a9-461a-b588-7e851599f91e)|
