### ISSUE TITLE
UI Planos - Remover informação de métrica

### ISSUE THREAD

**Issue by paulowhyte** [wisemonkeys-co/wise-billing#182]
<h2>Descrição</h2>

Remover coluna que descreve as métricas dos serviços da interface de listagem de planos.
Entendendo que um serviço pode ser compartilhado por vários eventos , e cada evento pode possuir uma métrica distinta, exibir uma única métrica pode causar falha de entendimento .

<h2>Objetivos</h2>

- Melhor coerência na exibição das informações

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-app

<h2>Detalhamento</h2>

![Screenshot 2024-12-05 at 17 09 08](https://github.com/user-attachments/assets/37a76ef6-04df-4e3f-80b7-a93ff9fad761)

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>

| Coluna métrica removida  |
|--------|
|![Screenshot from 2024-12-19 14-47-17](https://github.com/user-attachments/assets/abf70db3-c6b9-44a3-a819-7b9dbe1a0f2e)|
