### ISSUE TITLE
UI de configurações de sistema - Redefinir localidade padrão

### ISSUE THREAD

**Issue by paulowhyte** [wisemonkeys-co/wise-billing#184]
<h2>Descrição</h2>

Redefinir a localidade e fuso horários padrões como: 
- Brasil
- America/Sao_Paulo

<h2>Objetivos</h2>

- Integridade da interface de usuário

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-app

<h2>Detalhamento</h2>

![Screenshot 2024-12-12 at 15 26 45](https://github.com/user-attachments/assets/ed51a7ab-bec1-4e58-9c8a-aef617134195)

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>

| Alterada a moeda para USD e região para os Estados Unidos  | Tela após clicar na opção restaurar, mostrando as informações em português região Brasil e moeda R$ |
|--------|--------|
|![Screenshot from 2024-12-19 14-39-36](https://github.com/user-attachments/assets/1ffd15e1-6d26-47b7-a976-fb175baaa1ab)|![Screenshot from 2024-12-19 14-39-36](https://github.com/user-attachments/assets/136e5021-8ec4-4745-8824-7f7acb7ec272)|
