### ISSUE TITLE
UI de Plano tarifário - implementar feedback (hourglass) antes do retorno da consulta do plano

### ISSUE THREAD

**Issue by paulowhyte** [wisemonkeys-co/wise-billing#185]
<h2>Descrição</h2>

Entre a carga da página e a carga dos dados usuário fica sem feedback ou fica com o resultado da consulta anterior até a nova carga de dados.
Implementar feedback (hourglass) antes do retorno da consulta do plano

<h2>Objetivos</h2>

- Boas práticas de usabilidade

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-app

**Comment by alvarobhz** [comment]
<h2>Homologação</h2>

Segue abaixo video mostrando o carregamento de novos dados sem mostrar os dados carregados na consulta anterior, subistituindo pela barra de carregamento. 


[https://www.loom.com/share/f9ef10c7c0024708b1254909e80c3101?sid=2797b380-a97a-41b8-bfe6-85ececd452bb](url)
