### ISSUE TITLE
Teste issue

### ISSUE THREAD

**Issue by paulo-whyte** [wisemonkeys-co/wise-billing#53]
<h2>Teste</h2>

Descrever de forma abrangente a funcionalidade a ser implementada

<h2>Objetivos</h2>

- Objetivo de Negócio 1
- Objetivo de Negócio 2

<h2>Requisitos</h2>

- Requisito 1
- Requisito 2

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (task-start ... Não editar esta seção)

<h2>Detalhamento</h2>

**Comment by paulowhyte** [comment]
Não será feita
