### ISSUE TITLE
Criação tardia de Ordens de Venda

### ISSUE THREAD

**Issue by graziellyoliveira** [wisemonkeys-co/wise-billing#65]
<h2>Descrição</h2>

Criação de ordens na ingestão do primeiro evento tarifável do ciclo correspondente..
A criação de ordens de venda deve seguir condições definidas no atributo "billing.scheduling.createOn" .
Se igual a "startDate" a ordem de venda deve ser criada incondicionalmente no início do ciclo de faturamento.
Se igual a "firstEvent" só será criada se houver pelo menos um evento tarifável que justifique a existência da mesma.

<h2>Objetivos</h2>

- Sanitização da base de dados evitando-se a criação de ordens de venda desnecessárias.

<h2>Requisitos</h2>

- Ajustes dos logs dos serviços ocs-accounting e ocs-rating para evidenciar o momento da criação da ordem de venda.
- Migração de dados permitindo que o atributo "billing.scheduling.createOn" seja obrigatório a partir de então.
- Validar serviço de integração billing-order-checkout quanto ao preenchimento do atributo "billing.scheduling.createOn"

<h2>Serviços</h2>

### Tarefas relacionadas aos serviços/domínios:
[//]: # (Não editar esta seção ... task-start)
- [x] ocs-rating

<h2>Detalhamento</h2>

**Comment by paulowhyte** [comment]
<h2>Homologação</h2>

Criação de todas as ordens no início do ciclo

![Screenshot 2024-09-26 at 16 18 18](https://github.com/user-attachments/assets/077e5607-ff73-44b1-9d2d-6e3fd38ba316)

Criação só das ordens cujas contas tem o atributo createOn = startDate

![Screenshot 2024-09-26 at 16 39 58](https://github.com/user-attachments/assets/472592b0-6080-4709-b9ca-153834c70a81)
